applyapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from applyapp.views import ApplyCreateView, MyApplyList, ApplyDetailView, DecisionApply, Comment
from articleapp.views import index, ArticleDetailView, ArticleCreateView, ArticleUpdateView, MyArticleList

app_name = "applyapp"

urlpatterns = [
    path('create/', ApplyCreateView.as_view(), name='create'),
    path('list/', MyApplyList, name='list'),
    path('detail/<int:pk>', ApplyDetailView.as_view(), name='detail'),
    path('decision/', DecisionApply, name='decision'),
    path('comment/', Comment, name='comment'),

]

articleapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from articleapp.views import index, ArticleDetailView, ArticleCreateView, ArticleUpdateView, MyArticleList, \
    ArticleApplyList

app_name = "articleapp"

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('index/', index, name='index'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('mylist/', MyArticleList, name='mylist'),
    path('applylist/', ArticleApplyList, name='applylist'),

]

toy42/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('applys/', include('applyapp.urls')),
    path('comments/', include('commentapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applyapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models import Model, ForeignKey, CharField, TextField, FileField,IntegerField

from articleapp.models import Article


class Apply(Model):
    DECISION_CHOICES = (
        (1, '결정전'),
        (2, '수락'),
        (3, '거절'),
    )

    offer = ForeignKey(Article, on_delete=models.CASCADE, related_name='offer')
    applicant = ForeignKey(User, on_delete=models.CASCADE, related_name='applicant')
    work = CharField(max_length=20)
    language = CharField(max_length=50)
    framwork = CharField(max_length=50)
    answer = TextField(max_length=100)
    file = FileField(upload_to='files/', null=True)
    decision = IntegerField(default=1, choices=DECISION_CHOICES)
    comment = TextField(max_length=200, null=True, default="확인 전 입니다.", blank=True)

    def __str__(self):
        return '%s 프로젝트에 대한 %s의 지원' % (self.offer, self.applicant)

applyapp/forms.py
from django import forms
from django.db.models import CharField
from django.forms import IntegerField

from applyapp.models import Apply


class ApplyForm(forms.ModelForm):
    class Meta:
        model = Apply
        fields = ('offer', 'work', 'language', 'framwork', 'answer', 'file')

applyapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView

from applyapp.decorators import article_ownership_required
from applyapp.forms import ApplyForm
from applyapp.models import Apply
from articleapp.models import Article

has_ownership = [article_ownership_required, login_required]


@method_decorator(login_required, 'post')
@method_decorator(login_required, 'get')
class ApplyCreateView(CreateView):
    model = Apply
    form_class = ApplyForm
    template_name = 'applyapp/create.html'

    def form_valid(self, form):
        temp_apply = form.save(commit=False)
        temp_apply.applicant_id = self.request.user.id
        temp_apply.save()
        return super().form_valid(form)

    def get_success_url(self):
        print(self.request)
        return reverse('articleapp:index')


class ApplyDetailView(DetailView):
    model = Apply
    context_object_name = 'target_apply'
    template_name = 'applyapp/detail.html'



def MyApplyList(request):
    user = request.user
    applys = Apply.objects.filter(applicant_id=user.id)
    return render(request, 'applyapp/list.html', {'applys':applys})


def DecisionApply(request):
    if request.method == 'POST':
        applys = Apply.objects.filter(id=request.POST.get('id'))
        return render(request, 'applyapp/applydecision.html', {'applys': applys})


def Comment(request):
    if request.method == 'POST':
        apply = Apply.objects.filter(id=request.POST.get('id'))
        for i in apply:
            i.comment = request.POST.get('comment')
            if request.POST.get('yes'):
                i.decision = 2
            else:
                i.decision = 3
            article_id = i.offer_id
            i.save()
        article = Article.objects.filter(id=article_id)
        applys = Apply.objects.filter(offer_id=article_id)
        return render(request, 'articleapp/applylist.html', {'applys':applys, 'article':article})

applyapp/templates/applyapp/applydecision.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
{% for apply in applys %}
    <div style="text-align: center;margin: 4rem auto"  display="inline-block";>
    <form style="text-align: center;"id="commentform" action="{% url 'applyapp:comment'%}" method="post">
                    {% csrf_token %}

						<label for="comment">코멘트 작성</label>
						<textarea name="comment" id="comment"></textarea>
					 <div class="clearfix"></div>
			           <input name="yes" type="submit" id="yes" value="수락">
                        <input name="no" type="submit" id="no" value="거절">
        								<input type="hidden" name="id" value="{{apply.id}}">
                    <div class="clearfix"></div>
				   </form>
    </div>
{% endfor %}
        {% endblock %}

applyapp/templates/applyapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center;margin: 4rem 30%">
<form action="{% url 'applyapp:create'%}"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% for article in articles %}
    <input type="hidden" name="offer" value="{{article.id}}">
    {% endfor %}
    <input type = "submit" value="Add" class = "btn btn-info btn-sm"></form>
    </div>

{% endblock %}

applyapp/templates/applyapp/detail.html
{% extends 'base.html' %}
{% block content %}


	<div class="details">
		<div class="container">
			<h2>{{target_apply.offer.title}} 프로젝트</h2>
				<P>{{target_apply.applicant.username}} 님의 지원</P>
						<div class="det_text">

				<p> {{target_apply.work}}</p>
				<p> {{target_apply.language}}</p>
			</div>

			<div class="det_text">
				<p>framwork :{{target_apply.framwork}}</p>
				<p>answer :{{target_apply.answer}}</p>
			</div>
			<br><br><br>
			<p><a href="{{ target_apply.file.url }}"target="_blank">개인 프로젝트 pdf 열기</a></p>
			<form action="{% url 'applyapp:decision'%}" method="post">
								{% csrf_token %}
								<input type="hidden" name="id" value="{{target_apply.id}}">
								<input type="submit" value="결정하러가기">
							</form>
        </div>
    </div>
{% endblock %}

applyapp/templates/applyapp/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

  {% if user.is_active %}
    <div style="text-align: center;">
        <a href ="{% url 'applyapp:create' %}" class = "btn btn-info">Apply Project</a>
    </div>
<br><br><br>
    <table class = "table">
        <thead>
            <tr>
                <th scope = "col">#</th>
                <th scope = "col">지원분야</th>
                <th scope = "col">언어</th>
                <th scope = "col">프레임워크</th>
                <th scope = "col">프로젝트</th>
                <th scope = "col">Modify</th>
                <th scope = "col">진행상태</th>
            </tr>
        </thead>
        <tbody>
            {% for apply in applys %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a >{{apply.work}}</a></td>
                <td><a >{{apply.language}}</a></td>
                <td><a >{{apply.framwork}}</a> </td>
                <td><a href="{% url 'articleapp:detail' pk=apply.offer_id %}">링크</a> </td>
                <td><a class="btn btn-success btn-sm">Modify</a></td>
                {% if apply.decision == 1 %}
                <td><a >결정 전입니다!</a> </td>
                {% elif apply.decision == 2 %}
                <td><a >수락!</a> </td>
                {% else %}
                <td><a >거절</a> </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <div style="text-align: center;">

<h2>로그인 후 서비스를 이용하 실수 있습니다.</h2>
    </div>
{% endif %}
{% endblock %}