applyapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from applyapp.views import ApplyCreateView, MyApplyList, ApplyDetailView, DecisionApply, Comment
from articleapp.views import index, ArticleDetailView, ArticleCreateView, ArticleUpdateView, MyArticleList

app_name = "applyapp"

urlpatterns = [
    path('create/', ApplyCreateView.as_view(), name='create'),
    path('list/', MyApplyList, name='list'),
    path('detail/<int:pk>', ApplyDetailView.as_view(), name='detail'),
    path('decision/', DecisionApply, name='decision'),
    path('comment/', Comment, name='comment'),

]

articleapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from articleapp.views import index, ArticleDetailView, ArticleCreateView, ArticleUpdateView, MyArticleList, \
    ArticleApplyList

app_name = "articleapp"

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('index/', index, name='index'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('mylist/', MyArticleList, name='mylist'),
    path('applylist/', ArticleApplyList, name='applylist'),

]

toy42/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accountapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('applys/', include('applyapp.urls')),
    path('comments/', include('commentapp.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import ForeignKey, CharField, TextField, IntegerField, BooleanField, ImageField


class Article(models.Model):

    publisher = ForeignKey(User, on_delete=models.CASCADE, related_name='article')
    title = CharField(max_length=20)
    introduce = CharField(max_length=50)
    content = TextField(max_length=100,  default=' ')
    deadline = IntegerField( default= 0)
    activation = BooleanField(default=True)
    question = CharField(max_length=30, default=' ')
    thumbnail = ImageField(upload_to='images/', null=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '[%s] 의 [%s]' % (self.publisher, self.title)

articleapp/forms.py
from django.db.models import TextField
from django.forms import ModelForm
from django import forms

from articleapp.models import Article


class CreateArticleForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable',
                                                           'style': 'height: auto;text-align: left;'}))

    class Meta:
        model = Article
        fields = ['title', 'introduce', 'content','deadline','question', 'thumbnail']# '__all__' 설정시 전체 필드 추가

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models.fields.related import RelatedField
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, UpdateView
from django.views.generic.edit import FormMixin

from applyapp.models import Apply
from articleapp.decorators import article_ownership_required
from articleapp.forms import CreateArticleForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm

has_ownership = [article_ownership_required, login_required]


def index(request):
    article_list = Article.objects.all().order_by('-id')
    return render(request, 'articleapp/index.html', {'article_list':article_list})


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = CreateArticleForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.publisher_id = self.request.user.id
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk':self.object.pk})


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = CreateArticleForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk':self.object.pk})


def MyArticleList(request):
    user = request.user
    articles = Article.objects.filter(publisher_id=user.id)
    return render(request, 'articleapp/list.html', {'articles':articles})


def ArticleApplyList(request):
    if request.method == 'POST':
        a = request.POST.get('id')
        article = Article.objects.filter(id=a)
        applys = Apply.objects.filter(offer_id=a)
        return render(request, 'articleapp/applylist.html', {'applys':applys, 'article':article})

articleapp/templates/articleapp/applylist.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}
{% if user.is_authenticated %}
    <div style="text-align: center;">
        <a href ="{% url 'articleapp:create' %}" class = "btn btn-info">Add Project</a>

    {% for article in article %}
    <h4><a href="{% url 'articleapp:detail' pk=article.pk %}">
        {{ article.title }} Project 지원자 리스트
    </a></h4>
    </div>
<br><br><br>
        {% endfor %}
    <p></p>
    <table class = "table">
        <thead>
            <tr>
                <th scope = "col">#</th>
                <th scope = "col">분야</th>
                <th scope = "col">언어</th>
                <th scope = "col">프레임워크</th>
                <th scope = "col">작성자</th>
                <th scope = "col">Link</th>
                <th scope = "col">진행상태</th>
            </tr>
        </thead>
        <tbody>
            {% for apply in applys %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a >{{apply.work}}</a></td>
                <td><a >{{apply.language}}</a></td>
                <td><a >{{apply.framwork}}</a> </td>
                <td><a href="{% url 'applyapp:detail' pk=apply.pk %}">{{apply.applicant}}</a> </td>

                <td><a href="{% url 'applyapp:detail' pk=apply.pk %}"class="btn btn-success btn-sm">지원글로 이동</a></td>
                {% if apply.decision == 1 %}
                <td><a >결정 전입니다!</a> </td>
                {% elif apply.decision == 2 %}
                <td><a >수락!</a> </td>
                {% else %}
                <td><a >거절</a> </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <div style="text-align: center;">

<h2>로그인 후 서비스를 이용하실 수 있습니다.</h2>
    </div>
{% endif %}

{% endblock %}

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


    <div style="text-align: center;margin: 4rem 30%">
<form action="{% url 'articleapp:create'%}"  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
<input type = "submit" value="Add" class = "btn btn-info btn-sm"></form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}
{% block content %}


	<div class="details">
		<div class="container">
			<h2>{{target_article.title}}</h2>
			<div class="det_text">
			간단한 프로젝트 소개글
				<p> {{target_article.introduce}}</p>
			</div>
			<div class="det_pic">
				  <img src="{{ target_article.thumbnail.url }}" class="img-responsive" alt="">
			</div>
			<div class="det_text">
				내용
				<p> {{target_article.content | safe}}</p>
			</div>
			<div class="det_text">
				질문
				<p> {{target_article.question}}</p>
			</div>
			<ul class="links">
				  		 <li><i class="date"> </i><span class="icon_text">{{target_article.created_at}}</span></li>
				  		 <li><a href="#"><i class="admin"> </i><span class="icon_text">{{target_article.publisher}}</span></a></li>
				    </ul>
					<ul class="links_middle">
						{%  if target_article.publisher == user %}
			  		     <li><a href="{% url 'articleapp:update' pk=target_article.pk %}"><i class="title-icon"> </i><span class="icon_text">수정/삭제하기</span></a></li>
				  		 <li><i class="tags"> </i><span class="icon_text">모집글 마감하기</span></li>
						{% endif %}
						{% if user.is_active %}
				  		 <li class="last"><a href="{% url 'applyapp:create' %}"><i class="permalink"> </i><span class="icon_text">지원하기</span></a></li>
						{% endif %}
		  		    </ul>
						{%  if target_article.publisher == user %}

					<ul class="links_bottom">
						<li ><form action="{% url 'articleapp:applylist'%}" method="post">
								{% csrf_token %}
								<input type="hidden" name="id" value="{{target_article.id}}">
								<input type="submit" value="지원자보기">
							</form>
						</li>
		  		    </ul>
									{% endif %}


        <hr>
        {%  for comment in target_article.comment.all %}
            {%  include 'commentapp/detail.html' with comment=comment %}
        {%  endfor %}

        {%  include 'commentapp/create.html' with article=target_article %}

		</div>
				  
			</div>
	</div>

{% endblock %}

articleapp/templates/articleapp/index.html
{% extends 'base.html' %}
{%load static %}
{% block content %}


<div class="content">
	<div class="container">
			     <ul id="myList">
					 <li>
							{% for article in article_list %}
							<script type="text/javascript">
							var x = {{forloop.counter}}
							if (x % 3 == 1){
								document.write ( '<div class="l_g">');
								}
							</script>
							<script type="text/javascript">
								document.write ( '<div class="col-md-3 praesent">');
								document.write ( '<div class="l_g_r">');
								document.write ( '<div class="dapibus">');
							</script>

								<h4>{{article.title}}</h4>
								<p class="adm">Posted by <a href="#">{{article.publisher}}</a>  |  7 days ago</p>
								<a href="{% url 'articleapp:detail' pk=article.pk %}">
									<img src="{{ article.thumbnail.url }}" class="img-responsive" alt=""></a>
								<p>{{article.introduce }}</p>
						 <a href="{% url 'articleapp:detail' pk=article.pk %}" class="link">Read More</a>
							<script type="text/javascript">
								document.write ( '</div></div></div>');
							</script>
							{% if forloop.counter|divisibleby:3 %}
							<div class="col-md-3 integ">
								</div>
							{% endif %}
							{% if forloop.counter == 3%}
								 {% if user.is_authenticated %}
							<script type="text/javascript">
								document.write ( '<div class="l_g_r">');
								document.write ( '<div class="posts">');
								document.write ( '<h4>My Menu</h4>');
								document.write ( '<h6><a href="/articles/mylist">내가 작성한 모집글</a></h6>');
								document.write ( '<h6><a href="/applys/list">내가 지원한 프로젝트</a></h6></div></div>');
							</script>
						 		{% endif %}
							{% endif %}

							{% if forloop.counter|divisibleby:3 %}
							<div class="clearfix"></div>
							{% endif %}

							{% endfor %}


					</li>
			        <!----//--->

					<div class="clearfix"></div>
					 						 <br>

			      </ul>
	 </div>

	</div>
</div>
{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}
    <div style="text-align: center;">
        <a href ="{% url 'articleapp:create' %}" class = "btn btn-info">Add Project</a>
    </div>
<br>
<br><br><br>
    <p></p>
    <table class = "table">
        <thead>
            <tr>
                <th scope = "col">#</th>
                <th scope = "col">제목</th>
                <th scope = "col">작성자</th>
                <th scope = "col">내용</th>
                <th scope = "col">Modify</th>
                <th scope = "col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td><a >{{article.title}}</a></td>
                <td><a >{{article.publisher}}</a></td>
                <td><a >{{article.introduce}}</a> </td>
                <td><a class="btn btn-success btn-sm">Modify</a></td>
                <td><a class="btn btn-danger btn-sm">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


    <div style="text-align: center;margin: 4rem 30%">
        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
        <input type = "submit" value="Update" class = "btn btn-info btn-sm"></form>
    </div>


<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}